# Generated by Django 3.1 on 2024-03-24 14:32

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20240320_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageunits',
            name='store',
            field=models.ForeignKey(default=store.models.Store.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.userprofile'),
        ),
    ]
