# Generated by Django 3.1 on 2024-03-24 15:06

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20240324_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(default=store.models.Store.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AddField(
            model_name='store',
            name='image_of_store',
            field=models.ImageField(default='media/store.jpg', upload_to='stores/'),
        ),
    ]
