# Generated by Django 3.1 on 2024-03-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20240324_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='image_of_store',
        ),
    ]
