# Generated by Django 3.1 on 2024-03-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_store_image_of_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image_of_store',
            field=models.ImageField(default='media/store.jpg', upload_to='stores/'),
        ),
    ]
