# Generated by Django 3.1 on 2024-03-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_slot_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='mass_of_good_in_kgs',
            field=models.IntegerField(null=True),
        ),
    ]
